version: "3.3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  web:
    build: ./
    command: sh -c "
      python manage.py collectstatic --noinput &&
      python manage.py wait_for_db &&
      python manage.py makemigrations authentication &&
      python manage.py makemigrations administrator &&
      python manage.py makemigrations shop &&
      python manage.py migrate &&
      uwsgi --http :8000 --master --enable-threads --module ecomm.wsgi"
    environment:
      - DEBUG=1
      - ENV=development
    ports:
      - "8000:8000"
    depends_on:
      - db
