# Generated by Django 3.2.7 on 2021-09-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210917_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth',
            field=models.TextField(blank=True),
        ),
    ]
