# Generated by Django 3.2.7 on 2021-10-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_admintoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='phNumber',
            field=models.TextField(default='', unique=True),
        ),
    ]
